### ISSUE TITLE
cookies auth_headers value %7B%7D

### ISSUE THREAD

**Issue by rjonathan** [lynndylanhurley/ng-token-auth#101]

**Comment by mkhatib** [comment]
I am seeing this exact same issue, any idea what was the problem?

**Comment by vdsabev** [comment]
I'm seeing it as well. Basically, my `auth_headers` are an empty object `{}`

**Comment by nrahnemoon** [comment]
Same problem. Tagging on to this thread if anyone is able to find a solution.

**Comment by nrahnemoon** [comment]
I fixed it!  FYI, here's what was going on for me.  I had some extra validations in my User model (specifically on fields that didn't exist after I started using devise_token auth; e.g., password and password_confirmation).  So I just had to remove those extraneous validations, and everything works perfectly.  The gem was just having trouble updating the user.

**Comment by uriklar** [comment]
I'm also getting this issue with cookie being %7B%7D. No extra validations... Anyone find a solution for this?

**Comment by uriklar** [comment]
Been struggling with this for a few days and finally found my answer here:
http://stackoverflow.com/questions/30145395/ng-token-auth-not-persisting
Hope this works for whoever's reading this...
#110, #50
