### ISSUE TITLE
Redirect not logged in users to the login state?

### ISSUE THREAD

**Issue by brunomperes** [lynndylanhurley/ng-token-auth#102]
I couldn't find on the docs how to redirect a user if they're not logged in and are trying to opening a state that requires it. I've set the `emailSignInPath` to my `ui-router` state, but I'm not sure if that's what I should do.

I've found on the docs this validation to check whether if a user is logged in before opening a state, should I add a manual `$state.go()` after the promise is returned?
```
.state('admin', {
        url: '/admin',
        abstract: true,
        template: '<ui-view/>',
        resolve: {
          auth: function($auth) {
            return $auth.validateUser();
          }
        }
      })
```

Thanks!

**Comment by brunomperes** [comment]
Found a solution here: https://github.com/lynndylanhurley/ng-token-auth/issues/10

Just added a catch function on the resolve
```Javascript
.state('admin', {
        url: '/admin',
        abstract: true,
        template: '<ui-view/>',
        resolve: {
          auth: function($auth, $state) {
            return $auth.validateUser().catch(function(){
              // redirect unauthorized users to the login page
              $state.go('login');
            });
          }
        }
      })
```

**Comment by lynndylanhurley** [comment]
@brunomperes - you can also look at subscribing the [`auth:invalid` event](https://github.com/lynndylanhurley/ng-token-auth#authinvalid).

**Comment by searsaw** [comment]
I have tried subscribing to the `auth:invalid` event, but it doesn't seem to do anything.  This is part of my `run` block:

```javascript
.run(function($rootScope, $state, $log) {
  $rootScope.$on('auth:invalid', function(e) {
    $log.log('Inside the auth:invalid handler.');
    $state.go('login');
  });
});
```

It doesn't do anything though.  I have a `resolve` setup like in the docs.  It won't show the dashboard page, like it is supposed to, but I'm trying to redirect to the login here.

**Comment by Dashon** [comment]
I have the same issue, 'auth:invalid' is never called 

```javascript 
App.run(['$rootScope', '$location',
    function($rootScope, $location) {
        $rootScope.$on('auth:login-success', function() {
            $location.path('/movies');
        });
        $rootScope.$on('auth:invalid', function() {
            //never gets called
            $location.path('/');
        });
    }
]);
```

**Comment by Dashon** [comment]
Instead I used $auth.validateToken() along with the auth:validation-error event.

**Comment by angelxmoreno** [comment]
is there a seperate ticket for the `'auth:invalid'` issue? can we mark it here?

**Comment by dtelaroli** [comment]
For me it's not dispatching the event in the run block.

**Comment by DrakenZA** [comment]
dont close issues that are still around. Might make you feel better but its counter-productive, thnks.

**Comment by tpmullan** [comment]
This issue is still present for me.  $auth.validateUser().catch works, but auth:invalid is never called when the session expires or the token becomes invalid because it is out of state.  Is this seen as the correct behavior?

**Comment by jancel** [comment]
+1

**Comment by colmben** [comment]
Just some info from my own experience with this. To catch a session expiry, listen to the auth:session-expired event. Looking at the code, the auth:invalid event gets broadcast if there are no auth-headers at all in cookies/local storage. You can confirm this by manually deleting out that cookie while logged in and then try to move around your app. You can delete cookies manually in chrome by clicking on the lock or info icon at the left of the url in the omnibar. 

I've checked that both manually deleting the cookie and logging out and trying to go to an in-app url both broadcast auth:invalid for me. 

Here is my code to listen for those events :
```
        // Catch expired and invalid tokens and logout
        $rootScope.$on('auth:session-expired', function(event) {
            signOut(event);
        });
        $rootScope.$on('auth:invalid', function(event) {
            signOut(event);
        });

        function signOut(event){
            $auth.signOut();
            $state.go('signIn');
        }
```
