### ISSUE TITLE
Redirect if not authenticated

### ISSUE THREAD

**Issue by drtzack** [lynndylanhurley/ng-token-auth#103]
Here is my route

          $stateProvider
              .state('app', {
                  abstract: true,
                  templateUrl: 'tpl/app.html',
                  resolve: {
                    auth: function($auth) {
                      return $auth.validateUser();
                    }
                  }
            })
              .state('app.home', {
                  url: '/home',
                  templateUrl: 'tpl/home.html',
                  resolve: {
                    deps: ['$ocLazyLoad',
                      function( $ocLazyLoad ){
                        return $ocLazyLoad.load(['js/controllers/chart.js']);
                    }]
                  }
              })
and here is the events

        $rootScope.$on('auth:invalid', function(ev, reason) {
          alert('auth failed because');
        });
        $rootScope.$on('auth:validation-error', function(ev, reason) {
          alert('auth failed because');
        });
        $rootScope.$on('auth:login-error', function(ev, reason) {
          alert('auth failed because');
        });

event is not firing if user opens directly the page (in this case http://localhost/#/home) 
but it okays switching between the pages.

Any idea why?

**Comment by felipegs** [comment]
Same here!

**Comment by harpster604** [comment]
Same issue here...

**Comment by talhazekeriyadurmus** [comment]
Still got nothing.

**Comment by thebenwaters** [comment]
Ok so I haven't tested this with this specific package, but with another token solutions I had the same issue within ui-router. I had to not use the dot notation for child parent. I had to use the attribute parent within the child and it fixed it

**Comment by talhazekeriyadurmus** [comment]
I found alternate which names satellizer. For now it works perfect.

**Comment by felipegs** [comment]
@talhazekeriyadurmus  Do know if satellizer works if devise_token_auth?

**Comment by talhazekeriyadurmus** [comment]
I don't think so. But there is a ruby example.
https://github.com/sahat/satellizer/tree/master/examples/server/ruby

**Comment by felipegs** [comment]
Thanks @talhazekeriyadurmus  but the example is not complete..

**Comment by talhazekeriyadurmus** [comment]
Yeah you right. It seems not completed. I don't know ruby so can't help about this.
I am using php with laravel and the example works fine.
If you know php or one of this language in https://github.com/sahat/satellizer/tree/master/examples/server you can rewrite codes for ruby.

**Comment by lynndylanhurley** [comment]
Hey guys, sorry about the delay. Can someone please check if this is still an issue in `0.0.25-beta1`?

**Comment by jakcharlton** [comment]
@lynndylanhurley I would love to help on this one, but I am struggling to get anything to trap the event at all - hard to see if its even firing

If I put a catch in the router, then it's definitely caught so presumably the event is fired ... I just can't find anywhere to initialise or put my $rootScope error catchers at all

Where is it recommended to put the init of these event catchers?  (eventually I want to use them to redirect to a login page)

**Comment by jakcharlton** [comment]
@lynndylanhurley OK, made some progress I think, I was checking for the wrong event ... the docs are a little unclear, but I was looking for auth:login-error instead of auth:invalid (which is what validateUser() broadcasts)

To attach global events I used module.run 

``` coffeescript
myapp.run(['$rootScope' , ($rootScope) ->
  $rootScope.$on 'auth:invalid', (ev, reason) ->
    alert('auth failed')

  $rootScope.$on 'auth:validation-error', (ev, reason) ->
    alert('auth failed')

  $rootScope.$on 'auth:login-error', (ev, reason) ->
    alert('auth failed')
])
```

Using 0.0.24 I *don't* see the problem described - again maybe me missing something ... but I can navigate to the URL directly or via a click and both broadcast auth:invalid

**Comment by jakcharlton** [comment]
@lynndylanhurley OK - have managed to reproduce ... 

In the same browser window if I modify the URL it sends the event (or at least my handler catches it)

If I open up a new window and type the URL the auth: method in the route gets called, but either no event gets fired (auth:invalid) or something else is fired

**Comment by jakcharlton** [comment]
@lynndylanhurley and on some basic debugging, it looks like in the second window (the one where it doesnt work) the auth method on my route is being called twice 

Stepping through validateUser
```
if (this.dfd == null) 
```

First time through, this is null, so the event gets broadcast.

Second time through  this.dfd has a value, so no event

Oddly, I cant get my event handlers to bind before the ui-router auth method runs, meaning I don't respond to the first event, the handlers bind after the first validateUser, then the second valdiateUser doesnt broadcast

**Comment by Dashon** [comment]
This did not work for me either, instead I used $auth.validateToken() along with the auth:validation-error event.

**Comment by bvasseursiliconsalad** [comment]
Hi @lynndylanhurley,
I tried with the version 0.0.25-beta1but it is still an issue :/
Are you working on a fix ?

Thanks

**Comment by askobara** [comment]
Hello!
May be you can find solution here #134?

**Comment by lynndylanhurley** [comment]
Please see [this example](https://github.com/lynndylanhurley/ng-token-auth#example-using-angular-ui-router) in the readme for a demonstration of how to use access control with client-side routes.

**Comment by afossey** [comment]
Hi!
Same issue here :/ 
Sometimes auth:invalid is fired but the code inside the $on function is not executed
Waiting for the next release :)

Thanks

**Comment by truthSeekr** [comment]
I still have this issue... is there some workaround for that problem.

**Comment by dcunited001** [comment]
this is happening for me as well.  it's because the `auth:invalid` event is fired before before the $rootScope event handlers are set up.  

is there another way to go about this?

**Comment by dcunited001** [comment]
i'm just using the promise returned by `validateUser` when i authenticate.  i'm attaching the function below to the resolve for my routes.

```javascript
function authenticateRoute($auth, $state) {
  return $auth.validateUser()
    .catch(function(res) {
      $state.go('home');
    });
}

$stateProvider.state('user-profile', {
  url: '/users',
  resolve: {
    auth: authenticateRoute
  }
});
```

**Comment by truthSeekr** [comment]
thanks ! The function attached to resolve is the key !

**Comment by tenzai** [comment]
Yeah, thanks a lot, after two days of reading all the stuff about this awesome package this solved are my problems ! :D

**Comment by tiagozc** [comment]
Same issue here, the solution with promise returned by validateUser solve for while, but i don't think this should be a closed issue because the problem still exist!

**Comment by seanmavley** [comment]
Although https://github.com/lynndylanhurley/ng-token-auth/issues/103#issuecomment-125093104 is a great solution, it gets weird how to redirect user back to requested page after login, except it is way way easier doing so in the `$rootScope.$on( )` side in the `.run()` of angular.

The events don't fire, but if they do, at least how can I intercept them? They don't seem to work.

I'm targeting them using this, but doesn't work:

```
        $rootScope.$on("$stateChangeError", function(event, toState, toParams, fromState, fromParams, error) {
            if (error === "auth:validation-error" || error === "auth:invalid") {
                alert('auth failed'); // the broadcasts themselves don't even fire
                $state.go('login', { toWhere: toState });
            }
        });
```
