### ISSUE TITLE
Why are the functions added to the $rootScope instead of encapsulated in a service?

### ISSUE THREAD

**Issue by brunomperes** [lynndylanhurley/ng-token-auth#106]
I would like to understand this decision, as I think would feel more natural to be held inside a service and loaded only on services that need it?

Thanks!

**Comment by lynndylanhurley** [comment]
For easy access in templates.

**Comment by vdsabev** [comment]
This is generally advised against in the [AngularJS FAQ](https://code.angularjs.org/1.3.14/docs/misc/faq).

> Of course, global state sucks and you should use $rootScope sparingly, like you would (hopefully) use with global variables in any language. In particular, don't use it for code, only data. **If you're tempted to put a function on $rootScope, it's almost always better to put it in a service that can be injected where it's needed, and more easily tested.**

I'd prefer to at least be able to configure this behaviour. I don't want this to be in the root scope, and it's not even mentioned in the documentation, except for `$auth.authenticate`.
