### ISSUE TITLE
Cookie is not stored if client & server are on different domain

### ISSUE THREAD

**Issue by fikriauliya** [lynndylanhurley/ng-token-auth#110]
If the `apiUrl` is set to different domain (or even just different port), the cookie is never stored.

In my case, I run the client on Gulp serve (port 3001) and server on Rails (port 3000). If `apiUrl` is set to `http://localhost:3000`, the cookie is never stored. So I set proxy on Gulp to make all request under /auth and /omniauth path being forwarded to port 3000 and then set `apiUrl` to `http://localhost:3000` or just `` (empty). This way, the cookie could be stored.

However, in production environment it may happen that the domains are different (e.g. server at `api.example.com`, client at `www.coolsite.com`).

**Comment by lynndylanhurley** [comment]
On the demo site, the api is on a different domain than the client. I'm using a similar setup on several production sites, and I'm not seeing this issue.

Can you think of anything else that could be causing this behavior?

**Comment by fikriauliya** [comment]
Ok I will check :)

**Comment by fikriauliya** [comment]
I am not sure now. It works ok with both settings. Perhaps my browser cache or something else. Yesterday I tried changing different configuration.. Trying to replicate, but can't reproduce.

I think safe to close this :+1:

**Comment by lynndylanhurley** [comment]
Cool, thanks. Please re-open if the issue recurs.

**Comment by posixpascal** [comment]
I got the problem as well today, basically the $http interceptor can't access all of the response headers and therefore does not save the auth credentials. 
I started chrome using `--disable-web-security` and it worked so I think it has to do something with CORS. I restarted chrome with web-security enabled and it works now too...

The only difference is that my browser sent 2 requests, one OPTION request & one POST request. 
Maybe ignore option-requests in the response interceptor?

**Comment by uriklar** [comment]
I am also having this issue. Apps on different domain and no auth info being saved to the cookie. It doesn't get saved to local when I use that as well.

**Comment by posixpascal** [comment]
My webapp runs on the same domain as the api. I only had issues with CORS while debugging locally. :/

**Comment by RajatGoyal** [comment]
same issue here, I have tried everything, `auth_headers` is saved in localStorage only in disable security mode in chrome:

I have already set correct cors config to allow everything, my frontend and backend are on different domains.
```
    config.middleware.insert_before 0, "Rack::Cors" do
      allow do
        origins '*'
        resource '*',
                 :headers => :any,
                 :methods => [:get, :post, :delete, :put, :options, :head],
                 :expose  => ['access-token', 'expiry', 'token-type', 'uid', 'client'],
                 :max_age => 0
      end
    end
```
