### ISSUE TITLE
API and APP on the same host with omniauth

### ISSUE THREAD

**Issue by williamweckl** [lynndylanhurley/ng-token-auth#111]
I'm trying to authenticate with facebook using omniauth-facebook and devise-token-auth.

My APP is on the same host that the API, without any namespace. Tried to leave apiUrl empty and to put ip addresses like localhost:3000, lvh.me:3000, (myipaddress):3000 or 127.0.0.1:3000. In all cases, when facebook redirects me back, it redirect to `http://auth/facebook/callback#_=_`. Obviously, it doesn't work.

    @app.config ($authProvider) ->
      $authProvider.configure({
        apiUrl: '',
        authProviderPaths: {
          twitter:    '/auth/twitter',
          facebook:  '/auth/facebook',
          google:    '/auth/google'
        }
      });

If I put something like `/api`, it redirects to the right place. Unfortunately, I don't want to do that. I will not use any namespace. Just a subdomain, that I already tried too.

Tried to put the ip address on providers paths too. Doesn't work either.

**Comment by hoopoe** [comment]
How did you solve the problem?
