### ISSUE TITLE
locationProvider html5Mode preventing password reset

### ISSUE THREAD

**Issue by joekr** [lynndylanhurley/ng-token-auth#112]
In a project I had ng-token-auth working perfectly :+1: . Then ... we implemented ```$locationProvider.html5Mode(true)``` with Rails and now, it seems, the params aren't being parsed correctly. I see that issue [#31](https://github.com/lynndylanhurley/ng-token-auth/issues/31) talks a bit about something like this. 

**Version info**

* ng-token-auth: 0.0.24
* devise_token_auth: 0.1.30
* angular: 1.3.12
* rails: 4.2

I'm using Rails and devise_token_auth with ng-auth-token. Here is my setup:

 ``` javascript
.config( ($authProvider) ->
        $authProvider.configure(
            apiUrl: "<%= APP_CONFIG["auth_provider_url"] %>"
        )
)

app.config([ '$stateProvider', '$urlRouterProvider','$locationProvider'
  ($stateProvider, $urlRouterProvider, $locationProvider)->
    
    $stateProvider
        .state('auth',
            url: '',
            templateUrl: "navigation/navigation.html",
            controller: 'NavigationController',
            resolve: {
                auth: ($auth, $state) ->
                    return $auth.validateUser()
                        .catch( ()->
                            $state.go('public.log_in')
                         )
                user: ($auth) ->
                    return $auth.user
            }
        )
        .state('public',
            url: '',
            templateUrl: "public/index.html"
            controller: 'PublicController'
        )
        .state('public.forgot_password',
            url: '/forgot_password',
            templateUrl: "user/forgot_password.html",
            controller: 'UserForgotPasswordController'
        )
        .state('public.reset_password',
            url: '/reset_password',
            templateUrl: "user/reset_password.html",
            controller: 'UserResetPasswordController'
        )

    $locationProvider.html5Mode(true)
])

app.run( ($rootScope, $state) ->
  $rootScope.$on('auth:password-reset-confirm-success', () ->
    console.log('auth:password-reset-confirm-success')
    $state.go('public.reset_password')
  )
)
```

Then in my rails routes I have ```get '/app/*path' => 'app#index'```. If the user tries to reset their password they will get the following link:
``` 
http://local.dev/auth/password/edit?config=default&redirect_url=http%3A%2F%2Flocal.dev%2Fapp%2Fforgot_password&reset_password_token=YJam4MntXsz55LkPJu75
```
Once they click on it they are redirected to this link:
```
http://local.dev/app/forgot_password#%3Fclient_id=dP2ZKWyOMTSIHuMfdZjF4Q&config=default&expiry=&reset_password=true&token=XSkxunuleWGKtSL_W3il0A&uid=test@example.com
```
the "auth:password-reset-confirm-success" is never received and reseting the password they would get a ```401``` error.

If I simply remove ```$locationProvider.html5Mode(true)``` I receive "auth:password-reset-confirm-success" and it works great. The routing is handled, and the user is taken to ```app#/reset_password``` and they are able to reset.

My guess is it is something I'm doing wrong :frowning: , but I wanted to bring it up.

Thanks!

**Comment by lynndylanhurley** [comment]
That's strange - I'm using `html5Mode(true)` in several apps without any issues.

Is the redirect-url a valid URL?

~~~
http://local.dev/app/forgot_password#%3Fclient_id=dP2ZKWyOMTSIHuMfdZjF4Q&config=default&expiry=&reset_password=true&token=XSkxunuleWGKtSL_W3il0A&uid=test@example.com
~~~

Notice the `#%3F` between `forgot_password` and `client_id` - shouldn't that be a question mark(`?`)? 

My concern is that angular may not be detecting the querystring params.

Can you try manually replacing the `#%3F` in the URL with a question mark and re-loading the page?

**Comment by joekr** [comment]
Yeah the url is valid. Using vagrant and custom hosts file.

The ```#%3F``` should definitely be a ```?```. Sorry for not catching that :sweat_smile:. Looks like something on my Rails end is the issue.

Thanks for your time.

**Comment by joekr** [comment]
Sorry this might be more related to [devise_token_auth](https://github.com/lynndylanhurley/devise_token_auth/). 

If I override [```generate_url```](https://github.com/lynndylanhurley/devise_token_auth/blob/v0.1.32.beta1/app/models/devise_token_auth/concerns/user.rb#L214) and remove ```res += '#'``` on line [220](https://github.com/lynndylanhurley/devise_token_auth/blob/v0.1.32.beta1/app/models/devise_token_auth/concerns/user.rb#L220) it seems to work perfectly.

Again, I'm sure I have set something up wrong.

**Comment by mkhatib** [comment]
I am seeing the same problem. @joekr thanks for the pointer on a way to fix this for now.

**Comment by ryankc33** [comment]
+1 Getting this error as well
