### ISSUE TITLE
Can't get storage to work with custom authentication API

### ISSUE THREAD

**Issue by kevinfanomena** [lynndylanhurley/ng-token-auth#115]
Hi, I'm trying to use ng-token-auth to handle authentication with a custom authentication token API but can't get the storage (either cookie or local storage) to work after a call to submitLogin.

After a successful login (with password+email) my API responds with : 

```javascript
{ auth_token: "M8q6YXe3z4G1v5bx.3cfdd0778cdc3c6fded89426753cb06f4da314e395790fa5edee01750eb0c1d5", expires: "2015-02-18T16:36:35+00:00" }
```

I configured ng-auth-token thusly:

```javascript
$authProvider.configure({
    apiUrl: '/api',
    signOutUrl: '/auth/signout',
    emailRegistrationPath: '/auth/register',
    emailSignInPath: '/auth/signin',
    confirmationSuccessUrl: window.location.href,
    storage: 'localStorage',
    authProviderPaths: {
        facebook: '/auth/facebook'
    },
    parseExpiry: function(headers) {
        return headers.expires;
    },
    handleLoginResponse: function(response) {
        return response;
    },
    handleAccountResponse: function(response) {
        return response;
    },
    handleTokenValidationResponse: function(response) {
        return response;
    }
});
```

And my sign in function looks like 

```javascript
$scope.signin = function(credentials) {
    $auth.submitLogin(credentials)
        .then(function(resp) {
            console.log('then: ');
            console.dir(resp);
        })
        .catch(function(resp) {
            console.log('err: ');
            console.log(resp);
        });
};
```

The only thing being written to local storage is {currentConfigName: "default"}. Am I doing something wrong? I've been trying out all kinds of different settings but I just can't get it to work. Any help would be greatly appreciated.

**Comment by thebenwaters** [comment]
+1

**Comment by lynndylanhurley** [comment]
@kevinfanomena - did you read the section on [using custom header formats](https://github.com/lynndylanhurley/ng-token-auth#using-alternate-header-formats)?

The headers of each response to the API are checked against the keys of the `tokenFormat` hash in the config. It looks like you're using a non-default auth header (`auth_token`) - try passing this to the config:

~~~javascript
tokenFormat: {
  "auth_token": "{{ token }}"
}
~~~

**Comment by railslauncher** [comment]
@kevinfanomena You are returning the token details in response body(JSON). But token information should be in the response headers.

If you set the following headers it will work.

Access-Token, Uid, Expiry, Token-Type. Because I faced same issue.

**Comment by kevinfanomena** [comment]
Yes, I was returning the token in the response body and not the headers. Thanks for the help.
