### ISSUE TITLE
How can I set display types (page, popup, touch) for Facebook?

### ISSUE THREAD

**Issue by irfanfadilah** [lynndylanhurley/ng-token-auth#117]
As we know, Facebook have 3 types display options: page, popup and touch. And by default, when we click authenticate button, it's opening new tab (page type). So, how can I set display type to for e.g: popup?

**Comment by lynndylanhurley** [comment]
There is currently no support for this feature. I'll look into what it will take to roll it into the next release.

If you have the time, feel free to send me a PR.

**Comment by booleanbetrayal** [comment]
We're adding support for using the same window or an external window (new tab) for OAuth in an upcoming PR, but not specifically popup. Please feel free to submit a PR for that flow if still desired. Going to close this, but can re-open if needed.
