### ISSUE TITLE
Password change protection 

### ISSUE THREAD

**Issue by jakubrohleder** [lynndylanhurley/ng-token-auth#127]
Hi, I'm using ng-token-auth and devise_token_auth for a while now and it works perfectly in most cases, but there is one thing i cannot achieve and I haven't found solution in docs/issues: protecting password change.

 On most sites you see form with three fields: old password, new password and new password confirmation. It seems that with this gem/angular plugin you can change password of a logged user without knowing the old one (with $auth.updatePassword request). It seems a bit unsecure for me, is there any solution to this problem?

**Comment by lynndylanhurley** [comment]
I'll need to implement this feature. I'm working on pushing another release soon, I'll see if I can roll this feature in.

**Comment by JakubRohleder** [comment]
Great! I'm looking forward to see it in action!

**Comment by jakubrohleder** [comment]
How are the things going? Is there any way I can help you adding this feature? I think it is quite important to many folks form security point of view.

**Comment by booleanbetrayal** [comment]
@lynndylanhurley is taking some time off from this project, @jakubrohleder, but if you're willing to submit a PR for this, I think it's worthwhile. The only caveat is that this should be optional in order to be backwards compatible, and it should also not break the password reset flow. Are you using [devise_token_auth](https://github.com/lynndylanhurley/devise_token_auth) in conjunction with this module by chance?

**Comment by jakubrohleder** [comment]
@booleanbetrayal thank you for the answer! Yes I'm using this game along with [devise_token_auth](https://github.com/lynndylanhurley/devise_token_auth).

I'm not sure if I'm skilled enough to make this future alone, but tomorrow I'll look closer at it (both in this plugin and rails gem) and hopefully find a way to do it.

If it's ok in case of any questions/problems I'll report back to you.

**Comment by booleanbetrayal** [comment]
Sounds great!

**Comment by jakubrohleder** [comment]
It was pretty straightforward, so I did it today. Changes were mostly done in lynndylanhurley/devise_token_auth#317 this plugin required only a readme update.

**Comment by booleanbetrayal** [comment]
Sweet ... this looks good. Noticed you got the registrations_controller fix in as well. Thanks for the PR!

**Comment by jakubrohleder** [comment]
No problem! It was easier then I expected and surely will help making my project more secure ;).
