### ISSUE TITLE
doc-request: Docs for signedIn, others

### ISSUE THREAD

**Issue by olore** [lynndylanhurley/ng-token-auth#128]
Really enjoying this module. Thank you!

It took me a while to find **user.signedIn** as it is mentioned in the README, but only in an example. I'm guessing there are other useful functions that should be described in the documentation.

I'd love to contribute it if you also think it's worthwhile.

**Comment by booleanbetrayal** [comment]
@olore - If you find anything missing from the documentation, we'll be glad to accept PRs for fixes! Going to close this, but please submit any changes / additions you find that are missing!
