### ISSUE TITLE
Curl works but angular return 404...

### ISSUE THREAD

**Issue by robypez** [lynndylanhurley/ng-token-auth#135]
I have a problem with my request.

Using Angular Chrome browser return:
```
    OPTIONS http://example.it/api/v1/auth/sign_in 
    (index):1 XMLHttpRequest cannot load http://example.it/api/v1/auth/sign_in. Invalid HTTP status code 404
```
But trying with Curl
```
    curl -XPOST -v -H 'Content-Type: application/json' http://example.it/api/v1/auth/sign_in -d '{"email": "admin@example.it, "passoword": "administrator" }'
```
Everything is ok and return token...

Why?

**Comment by askobara** [comment]
Looks like your API doesn't support OPTIONS requests.
Did you use [devise_token_auth](https://github.com/lynndylanhurley/devise_token_auth) or your own implementation of API?

**Comment by robypez** [comment]
@askobara 

Devise Token Auth but I thing is a problem of CORS

**Comment by booleanbetrayal** [comment]
Closing stale issue. Please let me know if this is still a problem and we can re-open.
