### ISSUE TITLE
Uncaught Error: [$injector:modulerr]

### ISSUE THREAD

**Issue by andreydeineko** [lynndylanhurley/ng-token-auth#136]
I am trying to use `devise_token_auth` and `ng-token-auth` to establish authentication in my rails/angular app.

When gem is installed with its dependencies, bower installation is completed I add `ng-token-auth` module to my modules in` app.js`.

I've included 
"/js/angular/angular.js">
"/js/angular-cookie/angular-cookie.js">
"/js/ng-token-auth/dist/ng-token-auth.js">
 in my `index.html`
As it is stated in title it simply throws the error

`Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.2.28/$injector/modulerr?p0=app&p1=Error%3A%20…Fassets%2Fvendor-d246c56eb280352b7a4d132de7860475.js%3Fbody%3D1%3A25%3A170)`
Here is my question on SO:

http://stackoverflow.com/questions/29250184/uncaught-error-injectormodulerr-ng-token-auth
I hope you can tell what's the issue.

**Comment by lynndylanhurley** [comment]
I'm not sure what the issue is, but I'm certain that it isn't caused by this module.

Are you using any other modules that may have unmet dependencies?

**Comment by andreydeineko** [comment]
@lynndylanhurley, hey let me show you what modules I use:
   ` 'ngRoute',  'ngAnimate',  'ui.bootstrap',  'easypiechart',  'ui.tree',  'ngMap',  'ngTagsInput',  'angular-loading-bar'`

Please let me know, if I can provide any more of relevant info. Thanks a lot!

**Comment by andreydeineko** [comment]
Hey, the issue seem to go away after I've tossed the included modules in index.html. Thanks!

**Comment by vanntian** [comment]
edit ng-token-auth.js like this:
(function(){
    'use strict';
    angular.module('ng-token-auth', ['ipCookie']).provider('$auth', function() ...
})()
