### ISSUE TITLE
Login/Registration routes restricted after user validation

### ISSUE THREAD

**Issue by aihaddad** [lynndylanhurley/ng-token-auth#143]
Hi,

I was wondering if there's a way to restrict already signed in users from ever visiting the registration and login paths/routes and maybe redirect them somewhere else.

thanks

**Comment by askobara** [comment]
Hello,
See #134, maybe it would be helpful for you

**Comment by aihaddad** [comment]
Yes, that seems relevant.. Should've really looked thoroughly, not only relied on search. Thanks for pointing it out.
