### ISSUE TITLE
Handling 404 for locked users

### ISSUE THREAD

**Issue by stephenbaidu** [lynndylanhurley/ng-token-auth#149]
Is there an elegant way to handle sign in errors when a devise locked user tries to sign it. There does not seem to be any of the broadcasted events related to it. Hope someone can help.

**Comment by angelxmoreno** [comment]
What do you mean by `devise locked user`? Do you mean something like a user that is banned but has existing credentials ?

**Comment by stephenbaidu** [comment]
Exactly, a user that is banned. But I've resolved it now.
