### ISSUE TITLE
Which software did you use to create the "flow" schema ?

### ISSUE THREAD

**Issue by nicolas-besnard** [lynndylanhurley/ng-token-auth#160]
Like [this one](https://raw.githubusercontent.com/lynndylanhurley/ng-token-auth/master/test/app/images/flow/password-reset-flow.jpg)

**Comment by nicolas-besnard** [comment]
@lynndylanhurley any help ?

**Comment by szechyjs** [comment]
looks like [OmniGraffle](https://www.omnigroup.com/omnigraffle)

**Comment by wedneyyuri** [comment]
Also, you can use [Gliffy](https://www.gliffy.com/go/commerce/index)

**Comment by booleanbetrayal** [comment]
Good recommendations. Closing this!
