### ISSUE TITLE
Ionic + in app browser + cookies = doesn't work

### ISSUE THREAD

**Issue by otupman** [lynndylanhurley/ng-token-auth#162]
Found an interesting problem while trying to use ng-token-auth with cookie storage on Ionic but using ng-cordova-auth to handle my oauth process - the cookies get wiped. At least they do on Android. And, of course, having come out of the auth process ng-token-auth has lost it's auth tokens.

This appears to be due to the default configuration of the [in-app-browser](https://github.com/apache/cordova-plugin-inappbrowser) where it will clear the cookie cache before opening up the "new" browser window. 

It's a bit of a pain to find this problem as it'll only appear once one deploys to an emulator or device. 

Options I see are:
 - Detect the presence of the `cordova` object and maybe `console.warn` the developer
 - Include a note in the README.md either in the config section about the `storage` option 
 - Create a Cordova-specific section somewhere in the README to collect and deal with these (edge?) cases

I could do any of those, just not sure which is most appropriate.

**Comment by posixpascal** [comment]
:+1: +1 for cordova specific readme section.

**Comment by booleanbetrayal** [comment]
We're working on inAppBrowser support in an upcoming PR ... See also Issues #90 and #141 for tracking other implementations / etc. Going to close this, as documentation is also being addressed in the PR.

**Comment by booleanbetrayal** [comment]
The PRs are in for ng-token-auth #188 and devise-token-auth (lynndylanhurley/devise_token_auth#323). Please try these branches out and let us know if there are any issues in implementation. Will merge soon if no major issues are found!
