### ISSUE TITLE
How to integrate with Angular modules that uses jQuery AJAX

### ISSUE THREAD

**Issue by hybmg57** [lynndylanhurley/ng-token-auth#163]
For modules like Angular Datatables (https://l-lin.github.io/angular-datatables/) and FullCalendar ui-calendar (https://github.com/angular-ui/ui-calendar) they use jQuery AJAX instead of $http or $resource.

Is there a way to integrate this with ng-token-auth?

I did set 'beforeSend' option and set the headers retrieved from cookies for such as (access-token, client, uid) it works with 'devise-token-auth' nicely but after a few requests, the token becomes invalid and requests get 401. Is there something that I need to do in my response handlers to set these cookie key and values? How do I set them so I don't get 401 intermittently?

**Comment by booleanbetrayal** [comment]
@hybmg57 - you may want to take a look at [j-toker](https://github.com/lynndylanhurley/j-toker) instead of ng-token-auth, for jQuery AJAX calls. That being said, those projects should be using the angular $http provider, rather than jQuery AJAX. Hope this helps!

**Comment by tpmullan** [comment]
Something like the following code works for me.  You just have to update the tokens after each ajax call
```
angular.module('app')
    .run(runBlock)

    runBlock.$inject = [ '$auth'];
    function runBlock($auth ) {
      $.ajaxSetup({
        headers: $auth.retrieveData('auth_headers'),
        dataType: 'json'
      });

     $(document).ajaxComplete( function(ev, xhr, settings) {
        // set header for each key in `tokenFormat` config
        var newHeaders = {};

        // set flag to ensure that we don't accidentally nuke the headers
        // if the response tokens aren't sent back from the API
        var blankHeaders = true;

        // set header key + val for each key in `tokenFormat` config
        for (var key in $auth.getConfig().tokenFormat) {
          newHeaders[key] = xhr.getResponseHeader(key);

          if (newHeaders[key]) {
            blankHeaders = false;
          }
        }

        if (!blankHeaders) {
          $auth.setAuthHeaders(newHeaders);
        }
      });
    }

```
