### ISSUE TITLE
compatibility with ngCookies

### ISSUE THREAD

**Issue by HoplaGeiss** [lynndylanhurley/ng-token-auth#166]
I understood from your FAQ, that ng-token-auth is using ipCookie instead of ngCookies. However I am wondering why I can't use ngCookies and ng-toke-auth together ?

Since I use ng-token-auth I keep having unknown provider errors.

![screenshot from 2015-06-13 14 35 16](https://cloud.githubusercontent.com/assets/5755785/8144327/6fd3de7a-11d9-11e5-8983-fb5dfe972e94.png)

**Comment by piyushchauhan2011** [comment]
Same Problem here, when can we use ng-token-auth with ngCookies ?

**Comment by HoplaGeiss** [comment]
I just changed everything to use ipCookie.

**Comment by posixpascal** [comment]
Since the latest merge of master you can now write your own custom storage method by implementing 3 methods:

```javascript
var ngCookieStorage = {
    persistData: function(key, val){
        return $cookies.put(key, val);
    },
    retrieveData: function(key){
       return $cookies.get(key);
    },
    deleteData: function(key){
       return $cookies.remove(key);
    }
};

// on your ngTokenAuth config object set:
{
    "storage": ngCookieStorage
}
```

see #138 for more informations about this.
thank you @sgtpepper43 by the way.

**Comment by booleanbetrayal** [comment]
Closing this as there's now a mechanism that should accommodate any persistence implementation desired.

**Comment by piyushchauhan2011** [comment]
Thanks for the clarification :+1
