### ISSUE TITLE
redirection not working on ios safari

### ISSUE THREAD

**Issue by elhachimi** [lynndylanhurley/ng-token-auth#169]
Login with google for instance goes into the whole process but get stuck on the redirection page from the backend, seems that postMessage is not sent to the new tab till the origin tab is in focus.
just posted a related question in so: http://stackoverflow.com/questions/31007374/window-postmessage-to-a-new-tab-in-ios-safari?stw=2

**Comment by elhachimi** [comment]
this is fixed on ios 8

**Comment by NetanelBasal** [comment]
I have the same problem, did you found any solution to this?

**Comment by elhachimi** [comment]
yes, the problem is that the auth_headers was not set properly, what i did is setting by hand after authenticate or submit login like this:
``` 
$auth.authenticate(provider)
        .then(function(resp) {
          ipCookie('auth_headers', {
            // save the token
            'Authorization': 'Token ' + resp['auth_token'],
            'uid': resp['uid'],
            'expiry': resp['expiry']
          });
        })

**Comment by NetanelBasal** [comment]
From where the ipCookie function?

**Comment by elhachimi** [comment]
https://github.com/lynndylanhurley/ng-token-auth#why-does-this-module-use-ipcookies-instead-of-ngcookies

**Comment by NetanelBasal** [comment]
I did this in ios 8.1 and it is not seem to work?
