### ISSUE TITLE
Header not set in ios safari && chrome

### ISSUE THREAD

**Issue by elhachimi** [lynndylanhurley/ng-token-auth#171]
i can authenticate successfully with google auth but it seems that the header is not set on the http requests.

**Comment by angelxmoreno** [comment]
@elhachimi why did you close this?

**Comment by elhachimi** [comment]
Fixed it by setting the auth_header on registration

**Comment by angelxmoreno** [comment]
thanks @elhachimi was looking for confirmation about whether the module or we as developers had to do that.
