### ISSUE TITLE
Subdomain for cookies

### ISSUE THREAD

**Issue by Clempops** [lynndylanhurley/ng-token-auth#173]
I am using ng-token-auth for authentication linked with subdomains.
Ex: MyUser is sign in at first.domain.com. Cookies are set for first.domain.com, but I would like to set them for second.domain.com. For sign in, I use "submitLogin" method.
Is there a way to set the domain when signing in ?

**Comment by booleanbetrayal** [comment]
@Clempops - check out #138 which should allow for any implementation you want to implement. Feel free to close unless you have any questions.
