### ISSUE TITLE
recommended method to save user info

### ISSUE THREAD

**Issue by zh99998** [lynndylanhurley/ng-token-auth#174]
I'm using angular and ng-token-auth, it's awesome, and i have question about saving user info.

can ng-token-auth provide any help in saving user info (like email)? or i just have do it myself like without ng-token-auth?

**Comment by booleanbetrayal** [comment]
@zh99998 - There is the [$auth.updateAccount](https://github.com/lynndylanhurley/ng-token-auth#authupdateaccount) which will hit the endpoint specified by the `accountUpdatePath` [configuration value](https://github.com/lynndylanhurley/ng-token-auth#configuration). Hope that helps!
