### ISSUE TITLE
Safari does not get to message listener event and does not close the window

### ISSUE THREAD

**Issue by NetanelBasal** [lynndylanhurley/ng-token-auth#175]
I have a problem that in ios from version 8.2 and below the auth redirect does not close the window. i tried to debug this and i see that the code does not get to my console log: (i am using devise rails)

```javascript
window.addEventListener("message", function(ev) {
          console.log('here');
          if (ev.data === "requestCredentials") {
            ev.source.postMessage({
              <%= yield %>
            }, '*');

            window.close();
          }
        });
```

**Comment by booleanbetrayal** [comment]
iOS Safari should have full support for postMessage API - http://caniuse.com/#search=postmessage

I probably won't have time to dive into this in the next few weeks, so please let me know if you figure out what your issue is @NetanelBasal and if it requires a bug fix.

**Comment by NetanelBasal** [comment]
```javascript
                return this.t = $timeout(((function(_this) {
                  return function() {
                    return _this.requestCredentials(authWindow);
                  };
                })(this)), 500);
```

this script works fine in modern desktop browsers but in Ios Safari it seams like the original window setTimeout doesn't fire till it's on focus. Any work around to make the first window post message even if it's not on focus?

**Comment by NetanelBasal** [comment]
I dived into this and in the same IOS this is working on chrome but in safari the bug is that only if you switch to the original window the ##authWindow.postMessage("requestCredentials", "*");## is running and the process is continue as usual, so i think you should let know the users that use your plugin on this problem and try to find solution because we are consider now to change our system and this plugin because this bug. 

by the way i created the feature of "opening the auth provider in popup instead new tab" i will probably make pr in next week.

**Comment by booleanbetrayal** [comment]
Working on a PR where we will provide `sameWindow`, `newWindow`, and `inAppBrowser` implementations of OAuth sign-in flows. For now, it'll be up to the client code to decide which method is the most appropriate during ng-token-auth configuration. You can check out the branch here: https://github.com/lynndylanhurley/ng-token-auth/tree/improved_omniauth_flow

@NetanelBasal - If you would like to submit a PR (rebased against that branch perhaps) for some sort of modal popup interface instead, we'd gladly take a look. For now, going to update the docs in that branch and close this issue.

**Comment by NetanelBasal** [comment]
No problem, thanks.
