### ISSUE TITLE
Issue with $location.search

### ISSUE THREAD

**Issue by Chocksy** [lynndylanhurley/ng-token-auth#186]
I've made a new PR #185 that checks if $location.search is empty and if so then it tries to call a custom function to get the parameters of an url.

I was getting this problem when running an app with angular.js v1.3.9.

**Comment by booleanbetrayal** [comment]
Yeah, this appears to be a bug with older versions of angular not adhering to the RFC ... `$location.search()` parsing seems to work as expected with trailing fragments in 1.4.4.
