### ISSUE TITLE
User attributes

### ISSUE THREAD

**Issue by bighoax** [lynndylanhurley/ng-token-auth#187]
In this:

```
$rootScope.$on('auth:login-success', function(ev, user) {
  console.log(user);
});
```

I get user objects with all fields that it has on the back end side, which method does it hit on the back-end side? I m using devise_token_auth with rails. I would like to add some more data to the this user object on front end, to add some data from other models related to the user (on the back-end). 

How can I do that? Sorry for opening issue didn't know where to ask

**Comment by booleanbetrayal** [comment]
You can override your `as_json` method in your user model to return whatever additional data you'd like to be returned during serialization. Hope this helps!

**Comment by bighoax** [comment]
@booleanbetrayal appreciate it!

**Comment by booleanbetrayal** [comment]
Np!

**Comment by bighoax** [comment]
hey @booleanbetrayal without opening a new issue, or I can if you want, I have another question. How can I get the user info in the root scope? for  example :

```
$rootScope.$on('$routeChangeStart', function(event, next, current) {
       
});
```

How can I get the user info inside, `$routeChangeStart`. Is there a better place to ask this question?

**Comment by booleanbetrayal** [comment]
if successful authentication has already been conducted, the user info will be on `$rootScope.user`

**Comment by bighoax** [comment]
@booleanbetrayal @lynndylanhurley hey sorry to bother you guys again on this issue, I wanted to restrict the current user to access certain pages so I did something like this:

```
$rootScope.$on('$routeChangeStart', function(event, next, current) {
  permissionService.requestAccessToPage(next);        
});
```

And I inject to `$rootScope` into `permissionService` and inside `AccessToPage` method I check if the user object from the `$rootScope` is present or not and if it has the right properties to access this page.

Is there another/better way I can do this? Because this doesn't work when I refresh the page, when page is refreshed and when this code inside `AccessToPage` is reached, the `$rootScope.user` is always empty object.

However once I m logged in, and traverse to different pages without the full page reload, `$rootScope.user` is not empty object so that way I can either let that user pass trough the desired page or redirect them to login.

**Comment by booleanbetrayal** [comment]
The best way to deal with this sort of scenario, IMO is to use route resolvers. [Here's](http://odetocode.com/blogs/scott/archive/2014/05/20/using-resolve-in-angularjs-routes.aspx) decent primer. They're just promises that will resolve before the route change does. You can chain them, so you can ensure whatever validation call succeeds prior to any access check. The project README explains how to use them with angular-ui's router, but the same applies to vanilla route module.

**Comment by bighoax** [comment]
@booleanbetrayal thanks fantastic example thanks for your help

**Comment by booleanbetrayal** [comment]
np!
