### ISSUE TITLE
sameWindow flow

### ISSUE THREAD

**Issue by elhachimi** [lynndylanhurley/ng-token-auth#193]
In sameWindow section https://github.com/lynndylanhurley/ng-token-auth#ie8-11--ios-82-must-use-samewindow-for-provider-authentication explains that :
We should navigate from the API back to the client, is there any function that handles parsing url params in ng-token-auth module and how the url form must be ?

Edited : 
Found the url format i think it's this : https://github.com/lynndylanhurley/devise_token_auth/blob/master/lib/devise_token_auth/url.rb

What i need now is a way to handle it on the client side

**Comment by booleanbetrayal** [comment]
That's just a brief explanation of the process that will be handled if you use `sameWindow`.  i can see how it could be a little misleading. I might need to simplify that use-case explanation.

**Comment by booleanbetrayal** [comment]
Just tweaked!

**Comment by elhachimi** [comment]
Thanks, 
i want to understand the logic using sameWindow to implement it in a django-rest project.
if i understand, i'll need to hard redirect to auth_origin_url with user_token ... in the url params, do ng-token-auth handle it or i'll need to intercept it in ui-router
