### ISSUE TITLE
Cookie alternatives

### ISSUE THREAD

**Issue by bighoax** [lynndylanhurley/ng-token-auth#194]
Hello,

If I read the README correctly, once users authorizes and obtains the token from server, the token value is stored inside cookie so the user can reuse token to access authorized pages even if the page is refreshed.

My question is why not use something like https://github.com/nbubna/store to, to save the token value to session or local storage instead of cookie?

**Comment by angelxmoreno** [comment]
Read the docs. you can do that right now.
