### ISSUE TITLE
invite user

### ISSUE THREAD

**Issue by HoplaGeiss** [lynndylanhurley/ng-token-auth#199]
Very easy question. I must be missing something obvious.
How can you invite other people?
I mean creating them an account (signup) without actually changing your cookies.

Right now, I am using `submitRegistration` but when I refresh the page I am signed in as the new user I invited..

**Comment by angelxmoreno** [comment]
what do you mean by invite? This module has nothing to do with sending out invitations. Please reiterate.

**Comment by HoplaGeiss** [comment]
Never mind.. I forgot about this issue I opened.
As I said I wanted to signup someone without saving them in cookies.
But indeed, it has nothing to do with ng-token-auth. Sorry for the trouble
