### ISSUE TITLE
Add interceptor to catch 401 responses, hold http requests until user has been authenticated.

### ISSUE THREAD

**Issue by lynndylanhurley** [lynndylanhurley/ng-token-auth#2]

**Comment by AlejandroSilva** [comment]
in my app I use the following workflow:
1. the user access a restricted resource
2. the Apir responds with a 401 error
3. An interceptor get the error respond
4. show a login modal
    At this point several things can happen:

5.a.1 if the user close/cancel the modal
5.a.2 the request of the step 1 fails (finally), and a message is show
5.a.3 the usen can make another action, go to other page, etc.

5.b.1 if the use enter his credentials and authenticate correctly
5.b.2 the interceptor RESEND the request of the step 1, now with the new headers/credentials
5.b.3 the request now have to be successfull

The good of this aproach: don't need a queue for the request, the user can't go to another pages unless it close the modal or authenticate himself
