### ISSUE TITLE
Dont instantiate the controller before validate user

### ISSUE THREAD

**Issue by NetanelBasal** [lynndylanhurley/ng-token-auth#200]
My situation is like this:

1. I have two api's, one for auth users and one for non auth users.
2. In the controller i have function that send http request to the right api based if the user is authenticated or not.

The problem is the controller instantiate and send the request before the verify auth is finish the check and always send the http call to non authenticated api.

How i solve this problem?

**Comment by markhaasjes** [comment]
In the case you're using [ui-router](https://github.com/angular-ui/ui-router/wiki#resolve), you can use resolves to provide the controller with data before it's instantiated.

> If any of these dependencies are promises, they will be resolved and converted to a value before the controller is instantiated and the $stateChangeSuccess event is fired.

```javascript
$stateProvider.state('myState', {
      resolve:{
         // Example using function with returned promise.
         // This is the typical use case of resolve.
         // You need to inject any services that you are
         // using, e.g. $http in this example
         promiseObj:  function($http){
            // $http returns a promise for the url data
            return $http({method: 'GET', url: '/someUrl'});
         }
      }
});
```

Good luck!

**Comment by booleanbetrayal** [comment]
The standard angular router also supports resolver promises. This pattern is the best way to go about this, IMO.
