### ISSUE TITLE
token and client_id from InAppBrowser not persisted in ionic app on android

### ISSUE THREAD

**Issue by abhayastudios** [lynndylanhurley/ng-token-auth#208]
After reading the comment of @nbrustein here, I started to better understand the communication between ng-token-auth and the inAppBrowser. If I print the response from ng-token-auth's handleLoadStop function to the console I see that it contains the full user object including the auth_token and client_id (which corresponds to the last client_id in the database). Therefore I think I can conclude that the communication with InBrowserApp works fine and that the ionic app has access to the data.

However, any subsequent API requests to my server receive a 401 Not Authorized response. When I look at the request headers of those API requests I don't see any of the headers that Chrome on my laptop is sending to the server such as: access-token, client, expiry, token-type and uid.

If I print to the console the key and value of the persistData function when running on android and with InAppBrowser mode then immediately after the callback I see the correct data, e.g.:

````
key: auth_headers
value: Object {access-token: "<token>", token-type: "Bearer", client: "<client>", expiry: "1442773182", uid: "<uid>"}
````

However, on subsequent requests I see this:
````
key: auth_headers
value: Object {}
````

I also see that it tries to save the auth_headers in a cookie because it enters the switch default of the persistData function. Therefore I assume that somehow saving data through ipCookie does not work properly on ionic/android.

**Comment by abhayastudios** [comment]
Woohoo I got it working! Turns out that when working with ionic and I assume it is the same with cordova, storing the tokens according to default behavior in the cookie does not work. However, once you configure it to work with localStorage it works great!

**Comment by dtelaroli** [comment]
@abhayastudios I still getting error, can you help me?

```
external/chromium/net/disk_cache/storage_block-inl.h:119: [0909/210718:WARNING:storage_block-inl.h(119)] Failed data load.
W/chromium( 1032): external/chromium/net/disk_cache/storage_block-inl.h:119: [0909/210718:WARNING:storage_block-inl.h(119)] Failed data load.
W/chromium( 1032): external/chromium/net/disk_cache/storage_block-inl.h:119: [0909/210718:WARNING:storage_block-inl.h(119)] Failed data load.
E/chromium( 1032): external/chromium/net/disk_cache/entry_impl.cc:904: [0909/210718:ERROR:entry_impl.cc(904)] Failed to save user data
I/dalvikvm( 1032): Could not find method android.webkit.WebView.evaluateJavascript, referenced from method org.apache.cordova.inappbrowser.InAppBrowser$3.run
W/dalvikvm( 1032): VFY: unable to resolve virtual method 223: Landroid/webkit/WebView;.evaluateJavascript (Ljava/lang/String;Landroid/webkit/ValueCallback;)V
D/dalvikvm( 1032): VFY: replacing opcode 0x6e at 0x002e
W/PluginManager( 1032): THREAD WARNING: exec() call to InAppBrowser.injectScriptCode blocked the main thread for 27ms. Plugin should use CordovaInterface.getThreadPool().
D/CordovaLog( 1032): file:///android_asset/www/cordova.js: Line 1058 : processMessage failed: Error: TypeError: Illegal constructor
I/Web Console( 1032): processMessage failed: Error: TypeError: Illegal constructor at file:///android_asset/www/cordova.js:1058
D/CordovaLog( 1032): file:///android_asset/www/cordova.js: Line 1059 : processMessage failed: Stack: TypeError: Illegal constructor
D/CordovaLog( 1032):     at file:///android_asset/www/lib/ng-token-auth/dist/ng-token-auth.js:353:24
D/CordovaLog( 1032):     at Object.callbackFromNative (file:///android_asset/www/cordova.js:292:54)
D/CordovaLog( 1032):     at processMessage (file:///android_asset/www/cordova.js:1053:21)
D/CordovaLog( 1032):     at Function.processMessages (file:///android_asset/www/cordova.js:1090:13)
D/CordovaLog( 1032):     at pollOnce (file:///android_asset/www/cordova.js:955:17)
D/CordovaLog( 1032):     at pollOnceFromOnlineEvent (file:///android_asset/www/cordova.js:945:5)
I/Web Console( 1032): processMessage failed: Stack: TypeError: Illegal constructor
I/Web Console( 1032):     at file:///android_asset/www/lib/ng-token-auth/dist/ng-token-auth.js:353:24
I/Web Console( 1032):     at Object.callbackFromNative (file:///android_asset/www/cordova.js:292:54)
I/Web Console( 1032):     at processMessage (file:///android_asset/www/cordova.js:1053:21)
I/Web Console( 1032):     at Function.processMessages (file:///android_asset/www/cordova.js:1090:13)
I/Web Console( 1032):     at pollOnce (file:///android_asset/www/cordova.js:955:17)
I/Web Console( 1032):     at pollOnceFromOnlineEvent (file:///android_asset/www/cordova.js:945:5) at file:///android_asset/www/cordova.js:1059
D/CordovaLog( 1032): file:///android_asset/www/cordova.js: Line 1060 : processMessage failed: Message: S01 InAppBrowser125295987 [{"uid":"116642106272838797656","nickname":null,"image":"https:\/\/lh6.googleusercontent.com\/-oYjG0jh0_uY\/AAAAAAAAAAI\/AAAAAAAAAAA\/ENPxne79kt4\/photo.jpg?sz=50","auth_token":"NwV72kSXhKOjwNzpYM4bqQ","provider":"google_oauth2","expiry":1443042440,"message":"deliverCredentials","id":1,"updated_at":"2015-09-09T21:07:20.630Z","email":"denilson.silva@flexait.com.br","name":"Denilson Silva","config":null,"created_at":"2015-09-08T16:56:28.993Z","client_id":"pag3GyW7ih43Nyt33D2rHw"}]
I/Web Console( 1032): processMessage failed: Message: S01 InAppBrowser125295987 [{"uid":"116642106272838797656","nickname":null,"image":"https:\/\/lh6.googleusercontent.com\/-oYjG0jh0_uY\/AAAAAAAAAAI\/AAAAAAAAAAA\/ENPxne79kt4\/photo.jpg?sz=50","auth_token":"NwV72kSXhKOjwNzpYM4bqQ","provider":"google_oauth2","expiry":1443042440,"message":"deliverCredentials","id":1,"updated_at":"2015-09-09T21:07:20.630Z","email":"denilson.silva@flexait.com.br","name":"Denilson Silva","config":null,"created_at":"2015-09-08T16:56:28.993Z","client_id":"pag3GyW7ih43Nyt33D2rHw"}] at file:///android_asset/www/cordova.js:1060
```

**Comment by dtelaroli** [comment]
I created a new application and works.
Thanks

**Comment by aL3xa** [comment]
I have moved `auth_header` storage from cookies to localStorage, but I still get the freeze on `Redirecting...` page. @dtelaroli, can you please put some sample code to see how you handle authentication? FTR, I'm using plain Cordova, not Ionic.

**Comment by dtelaroli** [comment]
@aL3xa To fix the freeze I increase the timeout from the devise view https://github.com/lynndylanhurley/devise_token_auth/blob/master/app/views/devise_token_auth/omniauth_external_window.html.erb.
Create the view in your project but with 3000 milliseconds to test (line 31).

Folder: app/views/devise_token_auth
File: omniauth_external_window.html.erb

**Comment by aL3xa** [comment]
@dtelaroli, thanks for the update, but I still get the freeze after increasing the timeout value. Apparently, `message` event is not being fired at all, hence the page is stuck on `Redirecting...`. I have only these Cordova-specific JS lines:

```{js}
'use strict';

document.addEventListener('deviceready', function () {
  window.open = window.cordova.InAppBrowser.open;
  console.log('console.log works well');
}, false);
```

The Angular config section is pretty straightforward:

```{js}
  .config(function($authProvider, ENV){
    $authProvider
      .configure({
        apiUrl: ENV.apiEndpoint,
        omniauthWindowType: 'inAppBrowser',
        storage: 'localStorage',
        authProviderPaths: {
          google:   '/auth/google_oauth2',
          facebook: '/auth/facebook',
          twitter: '/auth/twitter',
          osm: '/auth/osm'
        }
      });
  })
```

Any ideas what may have caused "the freeze"?

**Comment by dtelaroli** [comment]
@aL3xa is it working if you debug at chrome? Can you find the logcat and chrome console for errors?

I configured for tests in android emulator and chrome (If your code is working fine at chrome the problema is confirmed at inAppBrowser).

It's possible test outside emulator to easy debugging (it's required configure your api account to localhost). I use the <code>ionic serve</code> to do that:

```
$authProvider.configure({
      omniauthWindowType: window.cordova == undefined ? 'newWindow' : 'inAppBrowser',
      storage: 'localStorage'
  });
```

Can you share one small project with your code connecting to an api test server?

**Comment by aL3xa** [comment]
I haven't tried it in Chrome (yet), as I'm debugging on android v4.1.x, but _weinre_ returns something that might come handy:

```{js}
Error in Success callbackId: InAppBrowser1226996874 : TypeError: Illegal constructor
```

I'll try it out on vanilla project and see if it works.
