### ISSUE TITLE
Showing navbar menu only if user authenticated.

### ISSUE THREAD

**Issue by jcarpanelli** [lynndylanhurley/ng-token-auth#213]
Hello there! I am developing an angularJS web application using ng-token-auth and an API using devise-token-auth in two separate apps. My main problem is that I want to hide (not really hide, but avoid rendering it) some html if there is no session started (So this html is not visible using 'inspect element') . Is this possible using angularJS?  I also think my problem here is about angularJS and not about this library in particular, but since I am using ng-token-auth and its "helpers" for managing sessions, I found appropriate to ask this question here.

Thanks.

**Comment by askobara** [comment]
Hello!
I think `ng-if="user.signedIn"` will help you
