### ISSUE TITLE
.success deprecated using $http

### ISSUE THREAD

**Issue by mateomarconi** [lynndylanhurley/ng-token-auth#219]
"The $http legacy promise methods success and error have been deprecated. Use the standard then method instead. If $httpProvider.useLegacyPromiseExtensions is set to false then these methods will throw $http/legacy error."

Replace to .then function.

[Reference](https://docs.angularjs.org/api/ng/service/$http)

**Comment by booleanbetrayal** [comment]
@mateomarconi - could you take a stab at converting the `success()` / `error()` to the `then()` conversion? i'll merge an PR with passing tests. have zero time to devote otherwise, atm.

**Comment by mateomarconi** [comment]
@booleanbetrayal - Yes, i can but i have not much time, I will check it the weekend ! i will create a new branch and PR you when test has finished.

**Comment by booleanbetrayal** [comment]
thanks @mateomarconi !

**Comment by mateomarconi** [comment]
@booleanbetrayal i do the changes but i cant test it, can you test for me please? and how i do a pull request if i cant push them to the repo? i have to put this in my own repo and then do a pull request? sorry for my ignorance!

**Comment by robinj** [comment]
@booleanbetrayal That's exactly how it works

**Comment by silaspedrosa** [comment]
+1
