### ISSUE TITLE
validateToken throws an error when server is unavailable

### ISSUE THREAD

**Issue by camolin3** [lynndylanhurley/ng-token-auth#224]
There is an error on `validateToken`, where it tries to access `data.errors` when `data` is null.
It is the same issue related to [this SO question](http://stackoverflow.com/questions/28120528/ng-token-auth-ui-router-resolver-causes-blank-screen), where it caused a blank page if it is called from a resolve with `ui-router`.  
It has a workaround (catch the error, to avoid blank page) but this seems like a bug that must be fixed.  
EDIT: I am using ng-token-auth v0.0.28.

**Comment by booleanbetrayal** [comment]
This should be fixed by #217 and available in v0.0.29-beta1. Going to close this, but can re-open if necessary.

**Comment by alain-andre** [comment]
I confirm, it fixes the problem.
