### ISSUE TITLE
Update npm version

### ISSUE THREAD

**Issue by sgtpepper43** [lynndylanhurley/ng-token-auth#250]
The version on npm is a year old, `0.0.24-beta1`. Could we get then newest version up on npm for those of use using webpack and similar?

**Comment by booleanbetrayal** [comment]
I don't have access to push to NPM atm. @lynndylanhurley will have to bump + push.

**Comment by lynndylanhurley** [comment]
@booleanbetrayal - I don't know what happened, but this guy now has control of the npm package:
https://www.npmjs.com/~dyaa

@dyaa - can we please have our project back?

**Comment by lynndylanhurley** [comment]
@dyaa - I apologize for my previous comment. I'm an idiot.

**Comment by brantchoate** [comment]
any update on this? We're referencing the git repo directly and it's getting pretty hard to manage. Thanks!

**Comment by lynndylanhurley** [comment]
I've been unable to contact @dyaa.

I just sent him an email, and I cc'd the npm dispute resolution team. So hopefully the problem will be resolved soon.

Sorry, this is a weird situation.

**Comment by dyaa** [comment]
@lynndylanhurley Can you check your email ...

**Comment by lynndylanhurley** [comment]
Got it, thanks @dyaa!! I’ll try to publish ASAP!

**Comment by booleanbetrayal** [comment]
thanks @dyaa!

**Comment by brantchoate** [comment]
Thanks!

**Comment by angelxmoreno** [comment]
please close this if resolved

**Comment by booleanbetrayal** [comment]
Pushed v0.0.29 to NPM yesterday!
