### ISSUE TITLE
Tokens on `ionic serve` and `ionic emulate -l`

### ISSUE THREAD

**Issue by duleorlovic** [lynndylanhurley/ng-token-auth#255]
We have learned that with Ionic we need to use `storage: 'localStorage'` #93 . But this helps only on real device (`ionic run`).

I could not get auth-tokens sent on ionic web (`ionic serve`). That really slows down my development since for everything I need `current_user`.

For emulator with live reload (`ionic emulate -l`) also the tokens are not sent (somehow validateUser is not called automatically on page load).

When I run on emulator without live reload, than works fine and I don't need to login again (although I need to run `ionic emulate` before each test).

Did anybody succeed to have *already logged in user* in ionic web or emulator with live reload ?

**Comment by gouroujo** [comment]
I have the same issue with $auth.submitLogin. The plugin is returned by the server but not stored in the locaStorage when I launch the app in the brower
This is a new issue but downgrading to an older version of the plugin don't seem to change anything.

**Comment by gouroujo** [comment]
I solved it by my own. For me, the issue was related to CORS problems with the browser and filtered headers properties. Using Ionic proxy solve the problem.
Check this article: http://blog.ionic.io/handling-cors-issues-in-ionic/

Hope it could help.

**Comment by duleorlovic** [comment]
This is not a CORS issue (I'm using rails rack-cors that allow *, and I have no problems fetching other resources like **api/posts** on `ionic serve` or `ionic emulate -l`).

 Problems is that on `ionic serve` or `ionic emulate -l` auth tokens are not sent (on `ionic emulate` or `ionic run` auth tokens are sent) .

**Comment by gouroujo** [comment]
The CORS security policies seems to have been recently updated in the major browsers. All the response body are accepted but the headers are often filtered.
If you want to check if your issue is related to the same issue I have faced, set up an http interceptor and log all the response headers. You should see the access-token in the response for the signin request.
I can advice you this very nice tutoriel to set up a ionic proxy to solve CORS issue: http://blog.ionic.io/handling-cors-issues-in-ionic/

**Comment by duleorlovic** [comment]
Yes @gouroujo you are right. I will investigate how. I missed this cors issue before. Thank you.

**Comment by pselle** [comment]
@duleorlovic I would love to know any outcome you had from your research!

**Comment by thelamborghinistory** [comment]
Running into same issue. I am only able to test this properly on a real device, which makes it really tedious. But I guess this is an Ionic issue in general, nothing about ng-token-auth itself.
