### ISSUE TITLE
Token persistence on sign in with email

### ISSUE THREAD

**Issue by simplylizz** [lynndylanhurley/ng-token-auth#260]
Hi,

I'm trying to implement sign in with email with your module and have met some problem: authentication token isn't persisted after submitLogin call. So when I refresh my page I'm loosing my session.

I've looked your code and found that there is no setHeader=true flag passed to handleValidAuth function:
https://github.com/lynndylanhurley/ng-token-auth/blob/master/src/ng-token-auth.coffee#L217

Could you explain why are you doing it in a such way? As for me I think that this flag should be passed everywhere and maybe even have default value setted to true.

Or maybe I've missed something and just using your module incorrectly?

P.S. Sorry, can't find any better place where I can ask my question. And also I'm a newbie in angularjs and maybe just misunderstanding some of concepts.

**Comment by simplylizz** [comment]
Sorry, my bad. My mistake was that backend didn't sent auth headers (but in any case I think it's not obvious behavior: login was succeed but nothing was persisted).

**Comment by FredHasselot** [comment]
Hi, i have a similare issue #280
Could you explain how you solved it on backend ?
thanks

**Comment by simplylizz** [comment]
Hi

I've described it in comment above: the problem had gone after I've added token info into related HTTP headers: access-token and expiry in my case.

**Comment by FredHasselot** [comment]
Hmmm,

i'm not sure to understand. you mean in the server side, rigth ?
I'm going to dig in this direction ...

thanks

**Comment by simplylizz** [comment]
Yes, on the server side. I'm implementing backend by myself.

**Comment by poc7667** [comment]
Did the documentation mention how to add the `HTTP headers: access-token`? I didn't see it. How could you do that?
Thanks

**Comment by simplylizz** [comment]
I'm talking about custom backend implementation so there is nothing about it in ng-token-auth docs.
