### ISSUE TITLE
Update NPM version

### ISSUE THREAD

**Issue by buccfer** [lynndylanhurley/ng-token-auth#281]
Please update npm version. Latest available version in npm is 0.0.24-beta1 but it should be 0.0.29-beta1.

**Comment by booleanbetrayal** [comment]
@lynndylanhurley / @dyaa  - I don't have write access to the NPM project. Can you add me?

**Comment by booleanbetrayal** [comment]
@lynndylanhurley - can you hook me up with NPM access now?

**Comment by lynndylanhurley** [comment]
Yes! Just a sec

**Comment by lynndylanhurley** [comment]
Just published. I wish I would give you access, but you will need to ask @dyaa for that.

**Comment by lynndylanhurley** [comment]
Actually I'm wrong - I was able to give you access.

~~~
❯ npm owner ls ng-token-auth
booleanbetrayal <brent.dearth@gmail.com>
dyaa <mail@dyaa.me>
lynndylanhurley <lynn.dylan.hurley@gmail.com>
~~~

**Comment by booleanbetrayal** [comment]
yay! how many months in the making?  =P

**Comment by booleanbetrayal** [comment]
Should be good @buccfer !

**Comment by lynndylanhurley** [comment]
lol it's literally been an international effort.

**Comment by buccfer** [comment]
Thanks very much. Appreciate that ;). Btw very nice plugin :)
