### ISSUE TITLE
Response 401 on post,  but i'm loggued

### ISSUE THREAD

**Issue by FredHasselot** [lynndylanhurley/ng-token-auth#284]
Hi,

I'm using devise_token_auth on the server side.
And ng-token-auth on the client side.

i can log-in and when i reload the app i'm still logged in.
i use localStorage.

Now when i send a Post request to save some texts on the database, i get a 401 response.
i use a filter like : " before_action :authenticate_user! ", on my controller on the server side.
(if i comment this filter, the request is successfull)

I don't understand what's happening.
The post request doesn't include the token? 
or is it a server side issue?

Thanks

**Comment by poc7667** [comment]
Same as yours. +1

**Comment by FredHasselot** [comment]
I'm still digging ...

i noticed that if i use a factory for interceptor like:

```
myApp.factory('BearerAuthInterceptor', function ($window, $q) {
    return {
        request: function(config) {
            config.headers = config.headers || {};
            if ($window.localStorage.getItem('auth_headers')) {
                config.headers.Authorization = 'Bearer ' + $window.localStorage.getItem('auth_headers');
                console.log($window.localStorage.getItem('auth_headers'));
            }
            return config || $q.when(config);
        },
        response: function(response) {
            if (response.status === 401) {
                //  something
            }
            return response || $q.when(response);
        }
    };
});

myApp.config(function ($httpProvider) {
    $httpProvider.interceptors.push('BearerAuthInterceptor');
});
```

then i get a request header containing this :
```
...
Authorization: Bearer {"access-token":"8di5RMv1qi-3oOP86Y1V7g","token-type":"Bearer","client":"hKK6Um68AUPqINoyInIxZQ","expiry":"1462806821","uid":"test@example.com"}
...
```

and if i don't use this factory i can't see "Authorization" mention or any "acces-token" things.
Default behaviours are not supposed to include auth-headers in the request ?

anyway, both tests return a 401 response...
but i can see token in the resource tab on chrome console 
something like:` {"access-token":"8di5RMv1qi-3oOP86Y1V7g","token-type":"Bearer","client":"hKK6Um68AUPqINoyInIxZQ","expiry":"1462806821","uid":"test@example.com"}`

and like i mentioned before, "auth:validation-success" return an object

**Comment by FredHasselot** [comment]
After i'm logged, when "auth:validation-success" return an object, i tested to add something like this on a controller rails: user_signed_in?  and it return false... 

i don't understand why $auth.validateUser return true and it's false on devise

**Comment by FredHasselot** [comment]
This : `{{ user.signedIn ? "true" : "false" }}` return true
but this on server side : user_signed_in? return false ...

why ?

**Comment by Bazarovay** [comment]
+1

**Comment by mrtomhoward** [comment]
I've been seeing the same thing when I connect to my production server on Heroku.
It's been working fine in development to my local Ubuntu VM.
I was also using localStorage.
I switched to cookies, and it works fine.

**Comment by angelxmoreno** [comment]
You can test what is sent to Device by using Chrome Developer tools. Perhaps diagnose that Device is setup correctly by using something like Postman or curl. At least that way you will know which of the two is the culprit.

**Comment by angryfeet** [comment]
I've just encountered the same issue. Check to see if the URL you're requesting matches the setting you've got for apiUrl.

My apiUrl setting was `'/api'` but the requests were being made to `'api'`, so because they didn't match the authorization headers weren't being set, resulting in the 401 error. I removed the leading forward-slash and it now works as expected.

**Comment by angelxmoreno** [comment]
@angryfeet good point. forgot to mention that
