### ISSUE TITLE
Need to do a full refresh to set proper access-token headers

### ISSUE THREAD

**Issue by cmosh** [lynndylanhurley/ng-token-auth#288]
All $http and $resource request to rails return a 401 ("you need to sign-in or sign-up  ), unless I perform a full browser refresh (ctrl + F5), only then do the requests get proper headers and return status 200. Using devise-token-auth as auth api in backend.

**Comment by angelxmoreno** [comment]
showing your $auth provider setup would help.

**Comment by cmosh** [comment]
var app = angular.module('myApp', ['ui.router','ng-token-auth','ui-notification','ngCart','restmod']);

app.config(function($stateProvider,$httpProvider,$urlRouterProvider,$authProvider,NotificationProvider) {
    $authProvider.configure({
            apiUrl: '/api'
        });

//Only declared the api url

**Comment by angelxmoreno** [comment]
If you properly format your code you increase the likelihood that someone might read it

```js
var app = angular.module('myApp', [
    'ui.router',
    'ng-token-auth',
    'ui-notification',
    'ngCart',
    'restmod'
]);
app.config(function($stateProvider, $httpProvider, $urlRouterProvider, $authProvider, NotificationProvider) {
    $authProvider.configure({
        apiUrl: '/api'
    });
```

**Comment by cmosh** [comment]
Will do the next I post code in an issue. I'm a little new at this. Anyway, I found the problem. It is because I was using Active Admin and had not done what was stated in the docs. I created a new controller with the devise-auth-token concerns but did not remove the concerns from the main application controller. So.. thanks for indulging me @angelxmoreno .

**Comment by angelxmoreno** [comment]
awesome! great job.
