### ISSUE TITLE
Headers not sent when using EventSource with SSE

### ISSUE THREAD

**Issue by a7medfahmy94** [lynndylanhurley/ng-token-auth#310]
I'm using EventSource in angular with SSE in a rails-api project.
using devise-token-auth and everything is working perfectly but, when it comes to the event stream, ng-token-auth doesn't add the authentication headers (access token).

I'm currently  connecting to the SSE using this
`new EventSource('/api/live_notifications?user_id='+user_id)`

Can anyone help me to get around this ?

**Comment by bslipek** [comment]
Does SSE have custom headers ?
Take a look: http://stackoverflow.com/questions/28176933/http-authorization-header-in-eventsource-server-sent-events

**Comment by a7medfahmy94** [comment]
I got around this issue with a simple (but bad) solution.
```
var params = "?user_id=" + user_id + "&access-token=" + token +
        "&client=" + client + "&uid=" + uid;
      PushNotification.eventSource = new EventSource('/api/live_notifications'+params)
```
closing this as it's not related to ng-token-auth
