### ISSUE TITLE
Failed to load resouce ios emulator

### ISSUE THREAD

**Issue by dandlezzz** [lynndylanhurley/ng-token-auth#319]
Hello!
I am working with an Ionic app and a rails backend using devise token auth. I am attempting to implement google_oauth2. When I run the ios simulator in live reload mode `ionic run ios -l -c -s` everything works fine. But for some reason when I build and then run in emulator mode I get a very frustrating error, I found it using the safari [debug trick](http://stackoverflow.com/questions/30339394/ionic-app-not-working-on-device-simulator). 

`Failed to load resource: You do not have permission to access the requested resource. http://localhost:3000//auth/googe_oauth2/callback`

I'm pretty sure the double slash isn't an issue but any help here would be appreciated. My only configuration option is localStorage.

**Comment by lee-wilkins** [comment]
@dandlezzz - Did you ever find a solution to this? I'm facing exactly the same issue.
