### ISSUE TITLE
Make a new release

### ISSUE THREAD

**Issue by thetomja** [lynndylanhurley/ng-token-auth#355]
[Release 0.0.29](https://github.com/lynndylanhurley/ng-token-auth/releases/tag/v0.0.29) was made exactly a year ago now, but there have been quite a few commits on the master branch since then, some of which fix some pretty critical issues.

Could you please make a new release from the latest master branch?

**Comment by ashpr** [comment]
Agreed on this. New users to the library keep getting tripped up.

**Comment by mattjegan** [comment]
👍  it's really annoying having to hardcode the commit hash into my `package.json`

**Comment by KristoferGoransson** [comment]
+1 Yeah, come on already. If you can't maintain this project then let somebody else do it...

**Comment by booleanbetrayal** [comment]
Just pushed / published v0.0.30.

**Comment by thetomja** [comment]
Yeah cheers mate nice one buddy thanks pal 😎 😎 😎

**Comment by KristoferGoransson** [comment]
Thank you! :+1:

**Comment by mattjegan** [comment]
Thanks 👍
