### ISSUE TITLE
Info on Support of this token for Angualr js 1.x

### ISSUE THREAD

**Issue by syedirfan7** [lynndylanhurley/ng-token-auth#356]
As i am trying to implement a login application using Rails+Angular.
My question is whether this library still supported for angular 1.x ? Do I need  to keep any extra items to make this work ?

**Comment by thetomja** [comment]
See https://github.com/lynndylanhurley/ng-token-auth/issues/355

The latest commit on master works brilliantly with 1.6.x, but for some reason they won't make a new release. So you'll have to install from the latest master commit instead of the latest official release 😕

**Comment by booleanbetrayal** [comment]
Just pushed / published v0.0.30 ... Should resolve the issues.
