### ISSUE TITLE
how to broadcast 'auth:logout-success' if i logout using my own method

### ISSUE THREAD

**Issue by iRajul** [lynndylanhurley/ng-token-auth#359]
This is more of a query. how to broadcast 'auth:logout-success' if i logout using my own method. 
i am calling my own method which logout but i want to broadcast 'auth:logout-success' , so that it will  destroy the uid and auth_token cookies saved client-side.

**Comment by thetomja** [comment]
`$rootScope.$broadcast('auth:logout-success')`
