### ISSUE TITLE
Using ng-token-auth with ngResource

### ISSUE THREAD

**Issue by joelwreed** [lynndylanhurley/ng-token-auth#36]
I might be doing something wrong but if I use ngResource methods, the token doesn't get passed to the server. If I use plain $http.get it does. Either way generates the same ajax GET call, but whatever ng-token-auth does to hook into $http doesn't seem to extend to ngResource. I tried with both latest angular 1.3rc0 and 1.2.23.

angular.module('spacetoolsApp')
  .controller('OrganizationsCtrl', ['$scope', 'Organization', '$http', function ($scope, Organization, $http) {
    // THIS NEXT LINE WORKS
    $scope.organizations = $http.get('http://www.spacetools.org/api/organizations.json');
    // THIS LINE DOESN'T SEND ACCESS TOKEN TO SERVER, THOUGH AJAX CALL IS THE SAME
    $scope.organizations = Organization.query();
  }]);

**Comment by williamweckl** [comment]
Helped me too man! Thank you.

**Comment by piyushchauhan2011** [comment]
Cool :+1:

**Comment by Cosmosz** [comment]
:+1:

**Comment by grantgeorge** [comment]
Hey yall - I just stumbled upon this when I was having an issue using ng-resource.

The path you pass in as a param to $resource has to explicitly match that of the apiUrl you provide for $authProvider. Example (didn't work for $resource, worked for $http):

```
$authProvider.configure({
    apiUrl: "api/v1"
});
```


```
.factory('Pitches', function ($resource) {
      return $resource('/api/v1/articles/:articleId', {
        articleId: '@id'
      }
      });
    });
```

It was not working because I did not include the forward slash in the beginning of the config. Fixed by changing the config to:

```
$authProvider.configure({
    apiUrl: "/api/v1"
});
```

Hope this may help someone stuck with this.

**Comment by piyushchauhan2011** [comment]
Yeah, we had the same problems and putting slash `'/'` in front of the `url` solved the issue. @grantgeorge

**Comment by gowthamgts** [comment]
@grantgeorge So, how should I provide the `apiUrl` if the API is running in an address like `http://localhost:3000`? TIA

**Comment by grantgeorge** [comment]
@gowthamgts try using a relative URL, ex '/' if that's the path to the appropriate resource (see my example). Is that your question?

**Comment by gowthamgts** [comment]
@grantgeorge No pal, I have to use a fully qualified name. The headers are not injected by default, but it is working fine now after I changed the storage option to `localStorage`. I guess the problem is with `ipcookies` may be. Thanks anyway...
