### ISSUE TITLE
Not sending autorization header with token

### ISSUE THREAD

**Issue by piernik** [lynndylanhurley/ng-token-auth#50]
I'm able to login (with login and password) (response is `{signedIn: true, configName: "default"}`).
But when I send new request to server in header I have no authorization header with Bearer /token/. why?
Here is request: 

```
$http.get('/user')
                                .then(function (resp) {
                                    $scope.resp=resp;
                                }); //I get 401
```

Here is my config:

```
$authProvider.configure({
                        apiUrl: '/angular-token/api',
                        tokenValidationPath: '/auth/validate_token',
                        signOutUrl: '/auth/logout',
                        emailSignInPath: '/auth/login',
                    });
```

Where using satellizer I have authorization header with all requests.

**Comment by uriklar** [comment]
Hi @lynndylanhurley,
I'm also not seeing the access-token headers in my requests. My Rails API (using the rails-api gem) is on a separate domain, using the rack-cors gem as configured in the devise_token_auth readme. 
Any idea why?
Thanks

**Comment by bentedder** [comment]
In case anybody runs across this later. Even though I was hitting the same domain, simply by putting the domain in, I was getting "Authorized users only." So changing to a relative path fixed it:

Changed from this:
```
$authProvider.configure({
     apiUrl: 'http://localhost:3000/api',
```
to this:
```
$authProvider.configure({
      apiUrl: '/api',
```
