### ISSUE TITLE
Support for devise's allow_unconfirmed_access_for

### ISSUE THREAD

**Issue by smarquez1** [lynndylanhurley/ng-token-auth#53]
I can configure devise to allow a user to sign in with an unconfirmed account, but on the ng-token-auth side, it still won't let me do it.

Also, if the option is configured, the user should be signed in automatically.

**Comment by asoules** [comment]
The instructions seem to be missing now. Is this still an option?

**Comment by ashwinputhige** [comment]
+1

"these instructions" points to a non existing link.
