### ISSUE TITLE
How to handle CSRF token issues

### ISSUE THREAD

**Issue by woutrbe** [lynndylanhurley/ng-token-auth#68]
In our current development setup, we have the Ruby back-end running on `http://localhost:3000` and the Angular front-end running on `http://localhost:4000`.

In the back-end we have `protect_from_forgery` enabled, since this is a cross-domain request the back-end is requesting a valid CSRF token for each non-GET request.

We're also using [devise_token_outh](https://github.com/lynndylanhurley/devise_token_auth) and [angular_rails_csrf](https://github.com/jsanders/angular_rails_csrf)

But without any luck, what's the proper way to handle this?

**Comment by duleorlovic** [comment]
Just to note that I have authorization problem when I completely remove `protect_from_forgery` method from ApplicationController.
It works when I leave it with condition as suggested [here](http://edgeapi.rubyonrails.org/classes/ActionController/RequestForgeryProtection.html)

~~~
  protect_from_forgery unless: -> { request.format.json? }
~~~

**Comment by Mrjaco12** [comment]
I think the use case for CSRF even with rotating tokens is if the token is stored in cookies.

**Comment by posixpascal** [comment]
Nah, I don't think it's a good option to store the CSRF token in the cookies because when then malicious websites could just POST forms to your backend and the CSRF token is automatically transmitted.

Therefore the CSRF token would be useless or not?

**Comment by Mrjaco12** [comment]
The CSRF wouldn't be in the cookies but the auth token would be there so that it's not accessible from XSS JS like localstorage or sessionstorage would be.
