### ISSUE TITLE
User is not accessible in controller

### ISSUE THREAD

**Issue by doronsever** [lynndylanhurley/ng-token-auth#72]
Hi
I'm trying to get the user object inside my controller after a successful login.
I want to use the data to do some REST queries.
I'm using a regular email / password authentication against my RUBY server (not facebook, github etc..)

If i console.log($auth.user) inside the controller i see an empty object. But, in my template, if i do {{user.email}} i do get the content.

```
 angular.module('myApp')
   .controller('myCtrl', function ($scope, $auth $rootScope ) {
    console.log($auth.user); //Empty object
    console.log(rootScope.user); //Empty object

   $scope.$auth = $auth;
   $scope.$watch('$auth.user', function(details){console.log(details);}); //Empty object
 });
```

I  tried to console.log($rootScope.user) without any success...
I also tried to $watch it but still no success.
I'm on Angular 1.34

Any ideas?

**Comment by absyah** [comment]
@lynndylanhurley  - I'm facing same problem. Not able to get User object in my controller. What should i do?
I just wanna to get user id in several controllers. e.g. as part of url redirection `user/:id`.
I tried `$scope.userId = $auth.user.id` but still no luck and it says that undefined for `$auth.user`.
Sorry i'm relative new to angular.

**Comment by absyah** [comment]
solved - I tried to use `$scope.userId = $rootScope.user.id` and it works. Sorry my bad :)

**Comment by manugb** [comment]
The actual "bug" is that first $auth.user is {} and after a few miliseconds its populated with the user data.
Thats why the log is {} but in the view you can see the data

what can I do to get the user populated from the beginning?
