### ISSUE TITLE
Facebook login redirects

### ISSUE THREAD

**Issue by nitingrewal** [lynndylanhurley/ng-token-auth#78]
After app access approval , The new window is redirecting to Login page & the new window is not getting closed. Suggestion welcome

app.config(['$authProvider', function ($authProvider) { 

    $authProvider.configure({
        apiUrl: '/api',

        authProviderPaths: {
            facebook: '/auth/facebook'

        }

  $scope.authFacebook = function() {
        
    $auth.authenticate('facebook')
                .then(function(response) {
                    $state.go('home');
                })
                .catch(function(error) {    
                    $scope.error = error.errors[0];
                });
        };

**Comment by lynndylanhurley** [comment]
@nitingrewal - sorry that this was neglected. I'm assuming that you've moved on, but please re-open this issue if you're still stuck. Also, I'll need you to post the source code from the page in question (not a link).
