### ISSUE TITLE
sample code without coffeescript

### ISSUE THREAD

**Issue by byunru** [lynndylanhurley/ng-token-auth#8]
Is it possible to provide sample code package that without using coffeescript?

**Comment by fikriauliya** [comment]
You can try this http://js2.coffee/ to convert coffee script codes into JS

**Comment by ACPK** [comment]
@lynndylanhurley  Feel free to close this as I'm all set.

**Comment by ingo777** [comment]
@ACPK 
Have you published your javascript example somewhere? I'm really interested in an example without coffeescript.

**Comment by uriklar** [comment]
+1 for a javascript sample app
