### ISSUE TITLE
Does this work with OAuth 2's implicit grant and Resource Owner Password Credentials ?

### ISSUE THREAD

**Issue by moneytree-doug** [lynndylanhurley/ng-token-auth#80]
I am looking through this library, and while it does say it supports OAuth facebook and twitter login, it doesn't explicitly say if it supports the other types of OAuth. Is this library usable with those few things?

**Comment by lynndylanhurley** [comment]
@moneytree-doug - the OAuth stuff happens on the server. I made a [rails gem](https://github.com/lynndylanhurley/devise_token_auth) for this project that supports OAuth using [omniauth](https://github.com/intridea/omniauth). omniauth supports [these strategies](https://github.com/intridea/omniauth/wiki/List-of-Strategies).

**Comment by lynndylanhurley** [comment]
@moneytree-doug - closing this issue, please re-open if I haven't answered your question.

**Comment by moneytree-doug** [comment]
@lynndylanhurley Its not exactly what I was looking for, but I appreciate the answer! Thanks!
