### ISSUE TITLE
ipCookie missing

### ISSUE THREAD

**Issue by jasenkoh** [lynndylanhurley/ng-token-auth#83]
Hello, 

I have angular app inside rails, with 'angularjs-rails' gem which is providing me ngCookies and I am injecting it successfully to angular app. But I am having issues with injecting ng-auth-token receiving following error:

<code>
 Uncaught Error: [$injector:modulerr] Failed to instantiate module bookApp due to:
Error: [$injector:modulerr] Failed to instantiate module ng-token-auth due to:
Error: [$injector:modulerr] Failed to instantiate module ipCookie due to:
Error: [$injector:nomod] Module 'ipCookie' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
</code>

Here's list of injected modules:

<code>
  var app = angular.module('bookApp', ['ngRoute',
    'ngResource',
    'ui.router',
    'templates',
    'ngCookies',
    'checklist-model',
    'ng-token-auth']);
</code>

**Comment by ltfschoen** [comment]
@booleanbetrayal Your answer is still coming in handy!
