### ISSUE TITLE
Websocket support

### ISSUE THREAD

**Issue by jakubjosef** [lynndylanhurley/ng-token-auth#84]
Hi everybody, 
i want to use this pretty looking module for my angular js application with Vert.x as backend.

So i want to send credentials (login (email), password) by Vert.x EventBus which is WebSocket JS library.
EventBus send data farther to auth module. 
Auth module do verification job and return some kind of sessionID.
If I know, this module is be able to use only with standard HTTP requests to URL, am I wrong?

Thank you for your help.

**Comment by lynndylanhurley** [comment]
All of the API requests in this module use [`$http`](https://docs.angularjs.org/api/ng/service/$http). I don't think `$http` supports websockets.

I haven't looked into websockets support yet. Can you recommend a good library?

**Comment by lynndylanhurley** [comment]
After doing some research, I've decided that websocket authentication makes more sense as a separate project. This module is meant to be used with a ReST API, and websocket apps don't really fit that paradigm.
