### ISSUE TITLE
Changing the action of submitLogin

### ISSUE THREAD

**Issue by c0mrade** [lynndylanhurley/ng-token-auth#86]
I use angular (and this gem) with rails.

If I have form like this :
``<form ng-submit="submitLogin(loginForm)" role="form" ng-init="loginForm = {}">``

And it's always hitting my route :
/api/auth/sign_in

However my api path is :
/api/v3/auth/sign_in

How do I change this to hit the right route?

**Comment by lynndylanhurley** [comment]
@c0mrade - have you read the [configuration section](https://github.com/lynndylanhurley/ng-token-auth#complete-config-example) of the readme?

If all of your routes start with `/api/v3`, I would recommend changing the `apiUrl` param to `/api/v3`.

##### Example:

~~~javascript
angular.module('myApp', ['ng-token-auth'])
  .config(function($authProvider) {
    $authProvider.configure({
      apiUrl: '/api/v3'
    })
  })
~~~

**Comment by c0mrade** [comment]
sweet thanks. Yes I have read it but I wasn't sure what was right thing to do. I'm new to angular. I had this suggestion before :

<form action="{{ ContextUrl + '/api/v1/auth/sign_in' }}">

Didn't like it. Your answer is much better. thanks again

**Comment by lynndylanhurley** [comment]
Cool, just re-open this issue if for some reason that doesn't work.
