### ISSUE TITLE
auth_headers not set

### ISSUE THREAD

**Issue by rgstephens** [lynndylanhurley/ng-token-auth#88]
I think I'm missing something basic about using ng-token-auth.  I'm successfully logging in with submitLogin. The token is returned from a Grails service I wrote in the payload data and I'm using persistData to store the token in handleLoginResponse.

```
      $auth.persistData('auth_headers', {
        'Authorization': 'Bearer ' + resp['token'],
      });
```
I can see that the data is stored in the cookie.

```
%7B%22Authorization%22%3A%22Bearer%202jqr4mak9r0qnql3irh2hor9e8m58u61%22%2C%22expiry%22%3A1420608106877%7D
```

However, when I use $response to make a call to my service, the token is not in the header.

**Comment by lynndylanhurley** [comment]
@rgstephens - have you set the `tokenFormat` config setting?

This module includes an `$http` interceptor that appends each property of the `tokenFormat` config setting to the headers of each request to the API (defined in the `apiUrl` param).

See [the docs](https://github.com/lynndylanhurley/ng-token-auth#using-alternate-header-formats) for more info on custom header formats.

**Comment by rgstephens** [comment]
Yes.  Here's the beginning of the config section:

```
app.config(function ($authProvider) {
  $authProvider.configure({
    apiUrl:                  serverRoot,
    emailSignInPath:         '/login',
    signOutUrl:              '/logout',
    tokenValidationPath:     '/auth/validate',
    emailRegistrationPath:   '/user',
    storage:                 'cookies',
    tokenFormat: {
      "Authorization": "Bearer {{ token }}"
    },
```

**Comment by thelamborghinistory** [comment]
I have this same issue with my Ionic app I think. My http basic auth header is not being sent.

```
$authProvider.configure({
    apiUrl: 'https://myapiendpoint.com',
    tokenFormat: {
      'Authorization': 'Basic ' + btoa('myuser:mypassword')
    },
    validateOnPageLoad: false,
    storage: 'localStorage'
  });
```
