### ISSUE TITLE
Heroku $rootScope.user get wrapper by 'user'

### ISSUE THREAD

**Issue by vs-zhang** [lynndylanhurley/ng-token-auth#89]
HI @lynndylanhurley 
When i deploy the sample app the heroku, the $rootScope.user have a very interesting bugs. I don't know that just me or what. Since in the localhost, the $rootScope is fine, it will be like
```
{_id: 123, name: 'abc', "email":"abc@aaa.com","provider":"email","uid":"123456","signedIn":true,"configName":"default"} 
```
But in heroku production env, it will be like 
```
{user: {_id: 123, name: 'abc', "email":"abc@aaa.com","provider":"email","uid":"123456"},"signedIn":true,"configName":"default"} 
```
as u can see, the $rootScope.user get wrapper

**Comment by lynndylanhurley** [comment]
What was the response from the `$auth.signIn()` / `$auth.authenticate()` method?

**Comment by vs-zhang** [comment]
![screen shot 2015-01-07 at 10 57 59 pm](https://cloud.githubusercontent.com/assets/3893244/5657704/c38716a2-96c0-11e4-860b-3a8f978c5c8d.png)

**Comment by vs-zhang** [comment]
that's the response from the heroku, in localhost is fine. And i know the demo is host in heroku, and that seems fine. Let me console.log more out to track what's going on. Total no idea

**Comment by lynndylanhurley** [comment]
That looks like the javascript `$auth.user` object. What was the response body from the server for the login request?

**Comment by vs-zhang** [comment]
![screen shot 2015-01-07 at 11 15 20 pm](https://cloud.githubusercontent.com/assets/3893244/5657800/23af1802-96c3-11e4-91b9-246477139b17.png)

This is the response back from the /api/auth/sign_in

**Comment by lynndylanhurley** [comment]
The server shouldn't be wrapping the data within a `user` object. Any idea why that's happening?

**Comment by vs-zhang** [comment]
![screen shot 2015-01-07 at 11 15 20 pm](https://cloud.githubusercontent.com/assets/3893244/5657823/9858ae02-96c3-11e4-81f9-c4d31e4f4a51.png)

and this is the response back from the localhost /api/auth/sign_in

**Comment by vs-zhang** [comment]
![screen shot 2015-01-07 at 11 18 51 pm](https://cloud.githubusercontent.com/assets/3893244/5657831/dd522402-96c3-11e4-92b4-53853763483e.png)

and this is the response back from the localhost /api/auth/sign_in

**Comment by lynndylanhurley** [comment]
So the problem is clearly with the API. Are both heroku and your local app running the same code (same app code, same gem versions, etc.)?

**Comment by vs-zhang** [comment]
the issue i found is so funny right now, since i am using a custom sessions_controller and i see the `@resource` is the same in local and heroku, they both like `<user _id:'123', name: abc>`, but when the next block
```
render json:{
          data: @resource.as_json(except: [
            :tokens, :created_at, :updated_at
          ])
}}
```
that's the fun start
in localhost it like
 `{:data=>{"_id"=>123, "email"=>"aa@abc.com", "name"=>"abc", "provider"=>"email"}`
in heroku it like 
 `{:data=>user=>{"_id"=>123, "email"=>"aa@abc.com", "name"=>"abc", "provider"=>"email"}}`

Localhost:
![screen shot 2015-01-08 at 12 13 57 am](https://cloud.githubusercontent.com/assets/3893244/5658169/5836bb7c-96cb-11e4-806a-9ba8fbb90a14.png)

Heroku:
![screen shot 2015-01-08 at 12 13 37 am](https://cloud.githubusercontent.com/assets/3893244/5658168/514cbf0a-96cb-11e4-9510-9a487f443b2a.png)

**Comment by vs-zhang** [comment]
@lynndylanhurley Thanks for all the help, the problem is the mongoid.yml in production session turn on the include_root_in_json: true, LOL

**Comment by lynndylanhurley** [comment]
Ahh no problem! :smiley:
