### ISSUE TITLE
angular-cookies

### ISSUE THREAD

**Issue by Kepro** [lynndylanhurley/ng-token-auth#91]
why you use angular-cookie and not angularJS NGcookie?? :) 
my project use ngcookie from angular and i love your project but loading two cookies modules...

**Comment by lynndylanhurley** [comment]
I just created an [faq section](https://github.com/lynndylanhurley/ng-token-auth#faq) just for this question.

The answer is [here](https://github.com/lynndylanhurley/ng-token-auth#why-does-this-module-use-ipcookies-instead-of-ngcookies), but I'll repeat:

It's impossible to control cookies' path values using ngCookies. This results in the creation of multiple auth tokens, and it becomes impossible to send the correct token to send to the API.

The only options were to re-implement cookie storage from scratch, or to use the [ipCookie module](https://github.com/ivpusic/angular-cookie). The ipCookie module seemed like the better choice, and it's been working well so far.

Please direct complaints regarding this problem to [this angualar issue](https://github.com/angular/angular.js/issues/1786).
