### ISSUE TITLE
http headers not being sent in Android

### ISSUE THREAD

**Issue by furkanayhan** [lynndylanhurley/ng-token-auth#93]
Maybe it is not an issue about `ng-token-auth`.

When testing on android phone or android simulator, requests don't include http headers such as token header for auth.
I can successfully sign in, but then no request being sent has http headers.

IOS emulator is working fine, but Android is not.

**Comment by furkanayhan** [comment]
More specific:
These headers are not sent by http request:
```
"access_token": "wwwww",
"token_type":   "Bearer",
"client":       "xxxxx",
"expiry":       "yyyyy",
"uid":          "zzzzz"
```

**Comment by furkanayhan** [comment]
I found the solution.
This `storage: 'localStorage'` config solved the problem:
```js
.config(function($authProvider) {
  $authProvider.configure({
    apiUrl: 'http://myprivateapidomain/api',
    storage: 'localStorage'
  });
})
```

**Comment by davidtlee** [comment]
This is great! Thanks @furkanayhan! Do you know why this works or what was the problem? Just wondering why it works without that setting in both browser and in iOS. Also wondering why adding that setting works still for browser and iOS in addition to android.

**Comment by davidtlee** [comment]
I guess the root question is when should we use localStorage vs. using cookies? Is there a best practice?

**Comment by furkanayhan** [comment]
@davidtlee  I think cookies are not enabled in ionic browser in android, but are enabled on ios.
However, localStorage are enabled on both of them.

**Comment by davidtlee** [comment]
Ahhhh, got it. Thanks!
