### ISSUE TITLE
Set apiUrl from $location

### ISSUE THREAD

**Issue by jdgblinq** [lynndylanhurley/ng-token-auth#94]
Hello,

In our application, we use $location to help us setup most of our URLs. For example, it might look a lot like this:

```
var url = $location.protocol()+'://'+$location.host()+':9080/api/v1'
```

We take this a step further and centralize this logic in a service called UrlService. One of my greatest frustrations with AngularJS has always been that I cannot inject services in the config function. ng-token-auth uses config to set the apiUrl:

```
angular.module('myApp', ['ng-token-auth'])
    .config(function($authProvider) {
        $authProvider.configure({
            apiUrl: 'http://api.example.com'
        });
    });
```

I can't even inject $location here. Is there a way to set the apiUrl after config()?

Thanks,

-- 
Jesse

**Comment by lynndylanhurley** [comment]
This is tough, because `$location` is only available during the run phase, and the `$auth` service needs to know the `apiUrl` before the run phase starts.

What is preventing you from just using `window.location` in this case?

**Comment by jdgblinq** [comment]
I'll do that. It's just very un-Angular. Maybe my entire UrlService needs to be a raw javascript object outside the Angular framework. yuck.

**Comment by lynndylanhurley** [comment]
From the [$window](https://docs.angularjs.org/api/ng/service/$window) docs:

> While window is globally available in JavaScript, it causes testability problems, because it is a global variable. In angular we always refer to it through the $window service, so it may be overridden, removed or mocked for testing.

My understanding is that the `$window` service exists solely for testing purposes (i.e. stubbing methods like `$window.open`). I don't think that purpose applies in this case.
