### ISSUE TITLE
ngCookies in .min.js file

### ISSUE THREAD

**Issue by rjonathan** [lynndylanhurley/ng-token-auth#96]
Hi, the .min.js file contains a ngCookies depence and doesn't seems to work. The no minify file seems good with ipCookie dependence.

**Comment by lynndylanhurley** [comment]
Thanks @rjonathan - I'll take a look ASAP.

**Comment by mrova** [comment]
I just lost an hour on this :P

**Comment by christian-fei** [comment]
Same here, would be nice if it could be fixed :)
Thanks for ng-token-auth!

**Comment by harpster604** [comment]
Just wasted an hour figuring this out too... .min.js file is using ngCookies while the other is using ipCookie.

**Comment by lynndylanhurley** [comment]
Ah sorry guys, I totally spaced on this. I'll push a fix tonight!

**Comment by lynndylanhurley** [comment]
Just fixed in `0.0.25-beta1`. Please confirm, thx!
