### ISSUE TITLE
ng-token-auth with multiple backends?

### ISSUE THREAD

**Issue by jdgblinq** [lynndylanhurley/ng-token-auth#97]
Hello,

I've got a frontend application using ng-token-auth and talking to a backend using devise_token_auth. For example, my apiUrl is something like ```http://backend1.somedomain.com/api/v1```. This works great.

Now I'd like to add another backend system on a different domain. For example, my apiUrl might be ```http://backend2.someotherdomain.com/api/v1```. This second backend would still use devise_token_auth, but it would use a different code base and separate database from the existing backend.

Is this possible with ng-token-auth? If so, how would I implement it?

Thanks!

-- 
Jesse

**Comment by jdgblinq** [comment]
@lynndylanhurley? Any input here? A simple "no, you can't do that, currently" would be fine if that's the answer.

**Comment by lynndylanhurley** [comment]
@jdgblinq - try following the [documentation for multiple user types](https://github.com/lynndylanhurley/ng-token-auth#using-multiple-user-types).

**Comment by jdgblinq** [comment]
If I setup multiple users, one for each apiUrl, will I be able to share a single token between them? Or will I have to login twice?

**Comment by jdgblinq** [comment]
Maybe I can programmatically login twice from the login form. But then that requires that the same user exists on both end points. Thanks, I think you've helped me walk out of this logic dilemma.
